DROP SCHEMA IF EXISTS dijkfood_schema CASCADE;
CREATE SCHEMA IF NOT EXISTS dijkfood_schema;
SET search_path TO dijkfood_schema;

CREATE TABLE USUARIO (
    USER_ID VARCHAR(255) PRIMARY KEY,
    PRIMEIRO_NOME VARCHAR(255) NOT NULL,
    ULTIMO_NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL, 
    ENDERECO_LATITUDE DECIMAL(10,8) NOT NULL,
    ENDERECO_LONGITUDE DECIMAL(11,8) NOT NULL
);

CREATE TABLE RESTAURANTE (
    REST_ID VARCHAR(255) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TIPO_COZINHA VARCHAR(100) NOT NULL, 
    ENDERECO_LATITUDE DECIMAL(10,8) NOT NULL,
    ENDERECO_LONGITUDE DECIMAL(11,8) NOT NULL
);

CREATE TABLE PRODUTOS (
    PROD_ID VARCHAR(255) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    REST_ID VARCHAR(255) NOT NULL,
    FOREIGN KEY (REST_ID) REFERENCES RESTAURANTE(REST_ID)
);

CREATE TABLE ENTREGADOR (
    ENTREGADOR_ID VARCHAR(255) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TIPO_VEICULO VARCHAR(50) NOT NULL, 
    ENDERECO_LATITUDE DECIMAL(10,8) NOT NULL,
    ENDERECO_LONGITUDE DECIMAL(11,8) NOT NULL
);

CREATE TABLE PEDIDOS (
    PEDIDO_ID VARCHAR(255) PRIMARY KEY,
    USER_ID VARCHAR(255) NOT NULL,
    REST_ID VARCHAR(255) NOT NULL,
    ENTREGADOR_ID VARCHAR(255) NOT NULL,
    CONFIRMED_TIME TIMESTAMP NOT NULL,
    PREPARING_TIME TIMESTAMP NOT NULL,
    READY_FOR_PICKUP_TIME TIMESTAMP NOT NULL,
    PICKED_UP_TIME TIMESTAMP NOT NULL,
    IN_TRANSIT_TIME TIMESTAMP NOT NULL,
    DELIVERED_TIME TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USUARIO(USER_ID),
    FOREIGN KEY (REST_ID) REFERENCES RESTAURANTE(REST_ID),
    FOREIGN KEY (ENTREGADOR_ID) REFERENCES ENTREGADOR(ENTREGADOR_ID)
);